name: Copilot Setup Steps

on:
  workflow_call:

jobs:
  copilot-setup-steps:
    name: Copilot Setup Steps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: opentofu/setup-opentofu@v2
      - name: OpenTofu Init
        run: tofu init -backend=false
