name: Copilot Setup Steps

on:
  workflow_call:

jobs:
  copilot-setup-steps:
    name: Copilot Setup Steps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: opentofu/setup-opentofu@v2
      - name: OpenTofu Init
        run: tofu init -backend=false
